name: labeler
on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  labeler:
    runs-on: ubuntu
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"